#!/bin/bash
# Generate additional card art for alchemy recipes
# Currently have 4 arts (guard, slash, heal, charge)
# Need to expand coverage for more card types based on alchemy_recipes.json

echo "Card Art Expansion Plan"
echo "======================="
echo ""
echo "Existing card art (4):"
echo "  1. card_art_guard.png - 守护/防御 (defense cards)"
echo "  2. card_art_slash.png - 斩击/攻击 (attack cards)"
echo "  3. card_art_heal.png - 治愈/回复 (heal cards)"
echo "  4. card_art_charge.png - 冲锋/蓄能 (charge/fire cards)"
echo ""
echo "Recipe mapping from alchemy_recipes.json (6 recipes):"
echo "  1. sprout_guardian (新芽守卫) - wood defense → card_art_guard.png ✓"
echo "  2. giant_shield (巨盾) - earth defense → card_art_guard.png ✓"
echo "  3. balanced_blade (平衡刃) - metal balanced → card_art_slash.png ✓"
echo "  4. bread_of_life (生命之粮) - light heal → card_art_heal.png ✓"
echo "  5. thorn_wall (荆棘壁) - earth defense → card_art_guard.png ✓"
echo "  6. harvest_sickle (收割镰) - fire attack → card_art_charge.png ✓"
echo ""
echo "Current coverage: 6/6 recipes covered by 4 card arts (using type-based matching)"
echo ""
echo "Expansion strategy:"
echo "  Option A: Element-specific art variants (16 total)"
echo "    - 4 types × 4 elements = 16 arts"
echo "    - guard_wood, guard_earth, guard_fire, guard_water"
echo "    - slash_metal, slash_fire, slash_wood, slash_water"
echo "    - heal_light, heal_wood, heal_water, heal_earth"
echo "    - charge_fire, charge_metal, charge_wind, charge_earth"
echo ""
echo "  Option B: Keep type-based (current 4) + add special cards"
echo "    - Keep current 4 generic type arts"
echo "    - Add 4-6 special/legendary card arts for unique effects"
echo "    - e.g., card_art_legendary_thorn.png, card_art_legendary_harvest.png"
echo ""
echo "Recommendation: Option B (incremental expansion)"
echo "  - Current 4 arts already provide good type coverage"
echo "  - Focus on making 4-6 standout legendary/special card arts"
echo "  - More cost-effective and visually impactful"
echo ""
echo "Priority special card art prompts:"
echo "  1. card_art_legendary_harvest.png"
echo "     'golden harvest sickle with fire runes, dramatic action pose, hand-painted fantasy card art, warm autumn tones, ornate border'"
echo ""
echo "  2. card_art_legendary_thorn.png"
echo "     'thorny earth wall with magical vines, protective stance, hand-painted fantasy card art, deep earth greens, ornate border'"
echo ""
echo "  3. card_art_legendary_shield.png"
echo "     'massive stone shield with ancient runes, immovable defense, hand-painted fantasy card art, granite grays and earth tones, ornate border'"
echo ""
echo "  4. card_art_legendary_blade.png"
echo "     'balanced crystal blade with metal essence, elegant strike, hand-painted fantasy card art, silver and gold accents, ornate border'"

